# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:145.0) Gecko/20100101 Firefox/145.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version_short} Safari/{webkit_version}', 'https://gitlab.gnome.org/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/ki11errabbit/.local/share/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set('content.local_content_can_access_file_urls', False, 'file:///home/ki11errabbit/.local/share/qutebrowser/userscripts/*')

# Keybindings
config.unbind('h', mode='normal')
config.unbind('j', mode='normal')
config.unbind('k', mode='normal')
config.unbind('l', mode='normal')
config.unbind('m', mode='normal')
config.unbind('n', mode='normal')
config.unbind('i', mode='normal')

config.unbind('H', mode='normal')
config.unbind('J', mode='normal')
config.unbind('K', mode='normal')
config.unbind('L', mode='normal')
config.unbind('M', mode='normal')
config.unbind('N', mode='normal')

config.unbind('tCH', mode='normal')
config.unbind('tCh', mode='normal')
config.unbind('tCu', mode='normal')
config.unbind('tIH', mode='normal')
config.unbind('tIh', mode='normal')
config.unbind('tIu', mode='normal')
config.unbind('tPH', mode='normal')
config.unbind('tPh', mode='normal')
config.unbind('tPu', mode='normal')
config.unbind('tSH', mode='normal')
config.unbind('tSh', mode='normal')
config.unbind('tSu', mode='normal')
config.unbind('tcH', mode='normal')
config.unbind('tch', mode='normal')
config.unbind('tcu', mode='normal')
config.unbind('th', mode='normal')
config.unbind('tiH', mode='normal')
config.unbind('tih', mode='normal')
config.unbind('tiu', mode='normal')
config.unbind('tl', mode='normal')
config.unbind('tpH', mode='normal')
config.unbind('tph', mode='normal')
config.unbind('tpu', mode='normal')
config.unbind('tsH', mode='normal')
config.unbind('tsh', mode='normal')
config.unbind('tsu', mode='normal')


config.unbind('h', mode='caret')
config.unbind('j', mode='caret')
config.unbind('k', mode='caret')
config.unbind('l', mode='caret')
config.unbind('H', mode='caret')
config.unbind('J', mode='caret')
config.unbind('K', mode='caret')
config.unbind('L', mode='caret')
config.unbind('e', mode='caret')

config.bind('m', 'scroll left', mode='normal')
config.bind('n', 'scroll down',mode='normal')
config.bind('e', 'scroll up',mode='normal')
config.bind('i', 'scroll right',mode='normal')

config.bind('M', 'back', mode='normal')
config.bind('N', 'tab-next',mode='normal')
config.bind('E', 'tab-prev',mode='normal')
config.bind('I', 'forward',mode='normal')

config.bind('j', 'search-next', mode='normal')
config.bind('J', 'search-prev', mode='normal')

config.bind('h', 'search-next', mode='normal')
config.bind('H', 'search-prev', mode='normal')

config.bind('t', 'mode-enter insert', mode='normal')

config.bind('lCH', 'config-cycle -p -u *://*.{url:host}/* content.cookies.accept all no-3rdparty never ;; reload', mode='normal')
config.bind('lCh', 'config-cycle -p -u *://{url:host}/* content.cookies.accept all no-3rdparty never ;; reload', mode='normal')
config.bind('lCu', 'config-cycle -p -u {url} content.cookies.accept all no-3rdparty never ;; reload', mode='normal')
config.bind('lIH', 'config-cycle -p -u *://*.{url:host}/* content.images ;; reload', mode='normal')
config.bind('lIh', 'config-cycle -p -u *://{url:host}/* content.images ;; reload', mode='normal')
config.bind('lIu', 'config-cycle -p -u {url} content.images ;; reload', mode='normal')
config.bind('lPH', 'config-cycle -p -u *://*.{url:host}/* content.plugins ;; reload', mode='normal')
config.bind('lPh', 'config-cycle -p -u *://{url:host}/* content.plugins ;; reload', mode='normal')
config.bind('lPu', 'config-cycle -p -u {url} content.plugins ;; reload', mode='normal')
config.bind('lSH', 'config-cycle -p -u *://*.{url:host}/* content.javascript.enabled ;; reload', mode='normal')
config.bind('lSh', 'config-cycle -p -u *://{url:host}/* content.javascript.enabled ;; reload', mode='normal')
config.bind('lSu', 'config-cycle -p -u {url} content.javascript.enabled ;; reload', mode='normal')
config.bind('lcH', 'config-cycle -p -t -u *://*.{url:host}/* content.cookies.accept all no-3rdparty never ;; reload', mode='normal')
config.bind('lch', 'config-cycle -p -t -u *://{url:host}/* content.cookies.accept all no-3rdparty never ;; reload', mode='normal')
config.bind('lcu', 'config-cycle -p -t -u {url} content.cookies.accept all no-3rdparty never ;; reload', mode='normal')
config.bind('lm', 'back -t', mode='normal')
config.bind('laH', 'config-cycle -p -t -u *://*.{url:host}/* content.images ;; reload', mode='normal')
config.bind('lah', 'config-cycle -p -t -u *://{url:host}/* content.images ;; reload', mode='normal')
config.bind('lau', 'config-cycle -p -t -u {url} content.images ;; reload', mode='normal')
config.bind('li', 'forward -t', mode='normal')
config.bind('lpH', 'config-cycle -p -t -u *://*.{url:host}/* content.plugins ;; reload', mode='normal')
config.bind('lph', 'config-cycle -p -t -u *://{url:host}/* content.plugins ;; reload', mode='normal')
config.bind('lpu', 'config-cycle -p -t -u {url} content.plugins ;; reload', mode='normal')
config.bind('lsH', 'config-cycle -p -t -u *://*.{url:host}/* content.javascript.enabled ;; reload', mode='normal')
config.bind('lsh', 'config-cycle -p -t -u *://{url:host}/* content.javascript.enabled ;; reload', mode='normal')
config.bind('lsu', 'config-cycle -p -t -u {url} content.javascript.enabled ;; reload', mode='normal')

config.bind('m', 'move-to-prev-char', mode='caret')
config.bind('n', 'move-to-next-line', mode='caret')
config.bind('e', 'move-to-prev-line', mode='caret')
config.bind('i', 'move-to-next-char', mode='caret')
config.bind('M', 'scroll left', mode='caret')
config.bind('N', 'scroll down', mode='caret')
config.bind('E', 'scroll up', mode='caret')
config.bind('I', 'scroll right', mode='caret')
config.bind('h', 'move-to-end-of-word', mode='caret')
