shadows=1
layer_shadows=1
gappoh=5
appov=10
borderpx=2

rootcolor=0xeff1f5ff
bordercolor=0x9ca0b0ff
focuscolor=0xea76cbff
urgentcolor=0xd20f39ff
scratchpadcolor=0x9ca0b0ff
globalcolor=0x9ca0b0ff
coverlayercolor=0x9ca0b0ff

windowrule=isterm:1,appid:Alacritty
monitorrule=name:DP-1,x:1080,y:300,width:2560,height:1440,refresh:120,vrr:1
monitorrule=name:DP-2,x:3640,y:577,width:1920,height:1080,refresh:60
monitorrule=name:HDMI-A-1,x:0,y:0,rr:3,width:1920,height:1080,refresh:60

tap_to_click=0
tap_and_drag=0
trackpad_natural_scrolling=1

exec-once=quickshell -n -c /home/ki11errabbit/.config/quickshell/getting-ready/
exec-once=noctalia-shell
exec-once=/home/ki11errabbit/.local/bin/configure-monitors.sh
exec-once=/home/ki11errabbit/.local/bin/setup-wallpaper.sh
exec-once=/home/ki11errabbit/.local/bin/setup-swayidle.sh
exec-once=/home/ki11errabbit/.local/bin/setup-keyboard.sh
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=mango
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

bind=SUPER,q,killclient
bind=SUPER,Return,spawn,alacritty
# d
bind=SUPER,d,spawn,noctalia-shell ipc call launcher toggle
# r
bind=SUPER,r,spawn,dolphin
# s
bind=SUPER,s,spawn,grimshot save area
bind=SUPER+SHIFT,s,spawn,grimshot copy area
bind=SUPER+SHIFT,Return,spawn,emacsclient -c -a 'emacs'
# n
bind=SUPER,n,focusstack,next
# e
bind=SUPER,e,focusstack,prev
# n
bind=SUPER+SHIFT,n,exchange_client,down
# e
bind=SUPER+SHIFT,e,exchange_client,up
# m
bind=SUPER+SHIFT,m,exchange_client,left
# i
bind=SUPER+SHIFT,i,exchange_client,right
# n
bind=SUPER+CTRL,n,focusdir,down
# e
bind=SUPER+CTRL,e,focusdir,up
# m
bind=SUPER+CTRL,m,focusdir,left
# i
bind=SUPER+CTRL,i,focusdir,right
bind=SUPER+CTRL,Return,zoom

# u
bind=SUPER,u,viewtoright
# l
bind=SUPER,l,viewtoleft

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

bind=SUPER,comma,focusmon,left
bind=SUPER,period,focusmon,right
bind=SUPER+SHIFT,code:59,tagmon,left
bind=SUPER+SHIFT,code:60,tagmon,right

# f
bind=SUPER,f,togglefullscreen
# m
bind=SUPER+ALT,m,incnmaster,+1
# i
bind=SUPER+ALT,i,incnmaster,-1
bind=SUPER+SHIFT,q,quit
# r
bind=SUPER+CTRL,r,reload

# t
bind=SUPER,t,setlayout,tile
# c
bind=SUPER,c,setlayout,scroller
# t
bind=SUPER+ALT,t,setlayout,vertical_tile
# c
bind=SUPER+ALT,c,setlayout,vertical_scroller

bind=NONE,code:123,spawn,noctalia-shell ipc call volume increase
bind=NONE,code:122,spawn,noctalia-shell ipc call volume decrease
bind=NONE,code:121,spawn,noctalia-shell ipc call volume muteOutput

bind=NONE,code:232,spawn,noctalia-shell ipc call brightness increase
bind=NONE,code:233,spawn,noctalia-shell ipc call brightness decrease


#bindsym XF86_AudioMicMute exec 'noctalia-shell ipc call volume muteInput'

#bindsym XF86Sleep exec 'noctalia-shell ipc call sessionMenu lockAndSuspend'
#
bind=NONE,code:172,spawn,noctalia-shell ipc call media playPause
bind=NONE,code:173,spawn,noctalia-shell ipc call media previous
bind=NONE,code:171,spawn,noctalia-shell ipc call media next
bind=NONE,code:225,spawn,noctalia-shell ipc call launcher toggle

bind=NONE,code:128,toggleoverview

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

gesturebind=none,left,3,viewtoright
gesturebind=none,right,3,viewtoleft
gesturebind=none,up,3,toggleoverview
gesturebind=none,down,3,toggleoverview

gesturebind=none,left,4,focusmon,left
gesturebind=none,right,4,focusmon,right

env=QT_QA_PLATFORM,qt6ct
env=XDG_CURRENT_DESKTOP,mango

enable_hotarea=0

