#!/bin/sh

SESSION="${1:-kak}"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    tmux new-session -d -s "$SESSION"
    tmux source-file "$SESSION" ~/.config/tmux/tmux-kakoune.conf 2>/dev/null
    tmux source-file ~/.config/tmux/tmux-kakoune.conf
fi

tmux attach-session -t "$SESSION"
