
# nop %sh{
#     mkdir -p "$kak_config/autoload"
#     ln -s "$kak_runtime/rc" "$kak_config/autoload/standard-library"
# }

hook global KakBegin .* %{
    nop %sh{
        if [ -n "$TMUX" ]; then
            tmux set-environment KAKOUNE_SESSION "$kak_session"
        fi
    }
}
# Width of a tab
set-option global tabstop 4

# Indent with 4 spaces
set-option global indentwidth 4

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# Display the status bar on top
set-option global ui_options ncurses_status_on_top=true

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Clipboard management mappings
map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -i<ret>"
map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"

# Shortcut to quickly exit the editor
define-command -docstring "save and quit" x "write-all; quit"

hook global WinCreate ^[^*]+$ %{editorconfig-load}

# Expand tabs to spaces



source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://github.com/jdugan6240/kak-bundle

bundle kakboard https://github.com/lePerdu/kakboard/ %{
    hook global WinCreate .* %{ kakboard-enable }
}

bundle smarttab.kak https://github.com/andreyorst/smarttab.kak %{
    set-option global softtabstop 4
    hook global WinSetOption filetype=* expandtab
    hook global WinSetOption filetype=makefile noexpandtab
    hook global BufOpenFile .* %{
        editorconfig-load
        autoconfigtab
    }
    hook global BufNewFile .* expandtab
    hook global BufNewFile Makefile noexpandtab
    hook global BufNewFile makefile noexpandtab
}

    hook global WinSetOption filetype=* expandtab
    hook global WinSetOption filetype=makefile noexpandtab
    hook global BufOpenFile .* %{
        editorconfig-load
        autoconfigtab
    }
    hook global BufNewFile .* expandtab
    hook global BufNewFile Makefile noexpandtab
    hook global BufNewFile makefile noexpandtab

bundle kakoune-registers https://github.com/Delapouite/kakoune-registers

bundle auto-pairs.kak https://github.com/alexherbo2/auto-pairs.kak %{
    hook global WinCreate .* %{ enable-auto-pairs }
}

bundle prelude.kak https://github.com/kakounedotcom/prelude.kak

bundle connect.kak https://github.com/kakounedotcom/connect.kak

bundle parinfer-rust https://github.com/eraserhd/parinfer-rust %{
    hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
        parinfer-enable-window -smart
    }
}
bundle-install-hook parinfer-rust %{
    cargo install --force --path .
}

bundle kak-rainbow https://github.com/Bodhizafa/kak-rainbow %{
	hook global WinSetOption filetype=(koka|rust|python|c|c\+\+|scheme|lisp|clojure|javascript|json|coq) %{
        rainbow-enable-window
	}
	set-option global rainbow_colors '#8839ef #ea76cb #dd7878 #e64553 #d20f39 #fe640b #df8e1d #40a02b #179299 #209fb5 #04a5e5 #1e66f5 #7287fd'
}

bundle kak-tree-sitter https://sr.ht/~hadronized/kak-tree-sitter/
bundle-install-hook kak-tree-sitter %{
    cargo install kak-tree-sitter
    cargo install ktsctl
}

bundle coqoune https://github.com/guest0x0/coqoune %{}

bundle-install-hook coqoune %{
    make
}

hook global WinSetOption filetype=coq %{
    coq-start
	declare-user-mode coq

	map buffer user c ": enter-user-mode coq<ret>" \
        -docstring "enter the Coq user mode"

    map buffer coq c ": enter-user-mode -lock coq<ret>" \
        -docstring "stay in the Coq user mode"

    map buffer coq k ": coq-back<ret>" \
        -docstring "undo last sent command"

    map buffer coq j ": coq-next<ret>" \
        -docstring "send the next command to Coq"

    map buffer coq <ret> ": coq-to-cursor<ret>" \
        -docstring "move tip to main cursor"
}

bundle-install-hook kakoune-lsp %{
    cargo install --locked --force --path .
    mkdir -p ~/.config/kak-lsp
    cp -n kak-lsp.toml ~/.config/kak-lsp/
}

bundle kakoune-lsp https://github.com/kakoune-lsp/kakoune-lsp %{
    eval %sh{kak-lsp}  # Not needed if you load it with plug.kak.
    lsp-auto-hover-enable
}

hook global WinSetOption filetype=(rust|python|c|cpp) %{
    lsp-enable-window
}

eval %sh{ kak-tree-sitter -dks --init $kak_session --with-text-objects -vvvvv }

# Set the colour scheme
#colorscheme doom-one
colorscheme catppuccin_latte

hook global WinSetOption filetype=rust %{
  hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
  hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
  hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
  hook -once -always window WinSetOption filetype=.* %{
    remove-hooks window semantic-tokens
  }
}

set-option global lsp_config %{
[language.rust.settings]
rust-analyzer.semanticHighlighting.nonStandardTokens = true
rust-analyzer.semanticHighlighting.strings.enable = true
rust-analyzer.semanticHighlighting.punctuation.enable = true
rust-analyzer.semanticHighlighting.punctuation.separate.macro.bang = true
rust-analyzer.semanticHighlighting.operator.enable = true
}

set-option global lsp_semantic_tokens %{
    [
        # items
        {face="attribute", token="attribute"},
        {face="type", token="enum"},
        {face="function", token="function"},
        {face="meta", token="derive"},
        {face="meta", token="macro"},
        {face="function", token="method"},
        {face="module", token="namespace"},
        {face="type", token="struct"},
        {face="type", token="trait"},
        {face="type", token="typeAlias"},
        {face="type", token="union"},

        # literals
        {face="value", token="boolean"},
        {face="string", token="character"},
        {face="value", token="number"},
        {face="string", token="string"},
        {face="meta", token="escapeSequence"},
        {face="meta", token="formatSpecifier"},

        # operators
        {face="operator", token="operator"},
        {face="operator", token="arithmetic"},
        {face="operator", token="bitwise"},
        {face="operator", token="comparison"},
        {face="operator", token="logical"},

        # punctuation
        {face="operator", token="punctuation"},
        {face="attribute", token="attributeBracket"},
        {face="operator", token="angle"},
        {face="operator", token="brace"},
        {face="operator", token="bracket"},
        {face="operator", token="parenthesis"},
        {face="operator", token="colon"},
        {face="operator", token="comma"},
        {face="operator", token="dot"},
        {face="operator", token="semi"},
        {face="meta", token="macroBang"},

        # misc
        {face="attribute", token="builtinAttribute"},
        {face="type", token="builtinType"},
        {face="comment", token="comment"},
        {face="variable", token="constParameter"},
        {face="meta", token="deriveHelper"},
        {face="variable", token="enumMember"},
        {face="type", token="generic"},
        {face="keyword", token="keyword"},
        {face="meta", token="label"},
        {face="meta", token="lifetime"},
        {face="variable", token="parameter"},
        {face="variable", token="property"},
        {face="keyword", token="selfKeyword"},
        {face="keyword", token="selfTypeKeyword"},
        {face="module", token="toolModule"},
        {face="type", token="typeParameter"},
        {face="Error", token="unresolvedReference"},
        {face="variable", token="variable"},

        # modifier overrides (more specific entries win)
        {face="variable", token="variable", modifiers=["mutable"]},
        {face="value", token="variable", modifiers=["constant"]},
        {face="function", token="function", modifiers=["unsafe"]},
    ]
}

face global InfoDefault               Information
face global InfoBlock                 Information
face global InfoBlockQuote            Information
face global InfoBullet                Information
face global InfoHeader                Information
face global InfoLink                  Information
face global InfoLinkMono              Information
face global InfoMono                  Information
face global InfoRule                  Information
face global InfoDiagnosticError       Information
face global InfoDiagnosticHint        Information
face global InfoDiagnosticInformation Information
face global InfoDiagnosticWarning     Information
